### PR TITLE
Add Slot model and dependencies

### PR DESCRIPTION
**Pull request by wolfrednicolas**
* remove Hold from the scheduler package
* add config
* add permissions
* add SchedulerServiceProvider with Slot
* Add Slot Factory
* Add migration to create slots table
* add Slot model
* add Nova slot
* add Slot policy
* add future slots filter
* add SlotPolicyTest
* add NovaCoreService Provider
* add NovaCoreService Provider
* add SlotDay filter for nova filters
* change the way to call the scopeVisibleBy method in the ScheduleEraser
* change the way to call the scopeVisibleBy method in the RecurringSchedule
* change the escape room version require to the `2.1.1`

### CODE REVIEW

**Comment by wolfrednicolas** [comment]
@sl0wik @drewroberts in order to finish this PR, is necessary to merge https://github.com/tipoff/support/pull/89 with the new namespaces for `Slot` and release a new version, and then change here the `composer.json`... besides there is another PR removing the Slot and dependencies from the `Bookings` model https://github.com/tipoff/bookings/pull/52

**Review by sl0wik — APPROVED** [review]

**Comment by wolfrednicolas** [comment]
@pdbreen any thought about this issue

`90) Tipoff\Scheduler\Tests\Unit\Models\SlotPolicyTest::all_permissions_not_creator with data set "delete-false" ('delete', class@anonymous/home/vagrant/code/packages-escape/scheduler/vendor/tipoff/test-support/src/BaseTestCase.php:217$230 Object (...), false)
Exception: Error: config/permission.php not found and defaults could not be merged. Please publish the package configuration before proceeding.`

**Comment by pdbreen** [comment]
Need to include the Spatie permissions provider `PermissionServiceProvider::class` in the TestCase provider array

https://github.com/tipoff/scheduler/blob/wolfrednicolas/feature/add-slot-model/tests/TestCase.php

**Review by drewroberts — APPROVED** [review]
Thank you! 🎎

**Comment by wolfrednicolas** [comment]
@drewroberts @sl0wik Cannot declare class CreateRatesTable, because the name is already in use in /home/runner/work/scheduler/scheduler/vendor/tipoff/bookings/database/migrations/2021_03_06_183050_create_rates_table.php on line 11

I saw you guys were talking about this topic on slack. this package call `escape-room` and `booking` package so there is a collision between them

**Review by drewroberts — APPROVED** [review]
Thank you! 🍧

**Pull request merged**
